version: "3.3"
networks:
  monitoring-networks:
    ipam:
      driver: default
      config:
        - subnet: "10.1.3.0/24"
services:

  node_exporter:
    image: prom/node-exporter
    container_name: node1-exporter
    hostname: node1-exporter
    ports:
    - '9100:9100'
    restart: always
    networks:
      - monitoring-networks

  cadvisor:
    image: 'google/cadvisor:latest'
    container_name: cadvisor
    hostname: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk:/dev/disk/:ro
    ports:
    - '8080:8080'
    restart: always
    networks:
      - monitoring-networks
